// src/components/Header.vue
<template>
      <div class="header h-12 fixed z-40 text-white mt-10 opacity-70 w-full font-body font-bold">
      <div class="header__inner flex justify-between mx-12 lg:mx-32">
        <div class="site-title">
          Godwin
        </div>

        <!-- d -->

        <div class="site-nav">
          <ul class="flex">
            <li class="mr-4">
              <a href="#about">About</a>
            </li>
            <li class="mr-4">
              <a href="#projects">Projects</a>
            </li>
            <li class="mr-4">
              <a href="#contact">Contact</a>
            </li>
          </ul>
        </div>

      </div>


    </div>
</template>

// src/lib/Header.svelte
<script>
	import { base } from '$app/paths';
</script>

<div class="h-4 pt-7 px-10 w-screen flex justify-between items-center fixed text-white">
	<div class="header-title"><a href="/">G.</a></div>
	<div class="header-links flex justify-between items-center gap-7">
		<div class="about"><a href="{base}/about">About</a></div>
		<div class="contact"><a href="{base}/contact">Contact</a></div>
	</div>
</div>
